services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
